# Generated by Django 5.2.17 on 2026-08-18 17:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricule",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="matricule"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=60, verbose_name="prénom (français)"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=60, verbose_name="nom (français)"),
                ),
                (
                    "first_name_ar",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="prénom (arabe)"
                    ),
                ),
                (
                    "last_name_ar",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="nom (arabe)"
                    ),
                ),
                (
                    "cin",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CIN invalide, ex. AB123456.",
                                regex="^[A-Za-z]{1,2}\\d{5,7}$",
                            )
                        ],
                        verbose_name="CIN",
                    ),
                ),
                (
                    "cnss_number",
                    models.CharField(blank=True, max_length=12, verbose_name="n° CNSS"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("teacher", "Enseignant(e)"),
                            ("admin", "Administration"),
                            ("support", "Personnel de soutien"),
                            ("direction", "Direction"),
                        ],
                        default="teacher",
                        max_length=10,
                        verbose_name="fonction",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro marocain attendu, ex. 0612345678 ou +212612345678.",
                                regex="^(\\+212|0)[5-8]\\d{8}$",
                            )
                        ],
                        verbose_name="téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="adresse")),
                (
                    "hire_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date d'embauche",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="salaire de base (DH)",
                    ),
                ),
                (
                    "allowances",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Primes mensuelles fixes soumises à cotisations et IR.",
                        max_digits=9,
                        verbose_name="primes imposables (DH)",
                    ),
                ),
                (
                    "dependents",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Conjoint et enfants, pour la déduction IR (max 6).",
                        verbose_name="personnes à charge",
                    ),
                ),
                (
                    "rib",
                    models.CharField(
                        blank=True,
                        help_text="Relevé d'identité bancaire (24 chiffres).",
                        max_length=24,
                        verbose_name="RIB",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teachers",
                        to="core.subject",
                        verbose_name="matières enseignées",
                    ),
                ),
            ],
            options={
                "verbose_name": "employé(e)",
                "verbose_name_plural": "employé(e)s",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="année")),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Janvier"),
                            (2, "Février"),
                            (3, "Mars"),
                            (4, "Avril"),
                            (5, "Mai"),
                            (6, "Juin"),
                            (7, "Juillet"),
                            (8, "Août"),
                            (9, "Septembre"),
                            (10, "Octobre"),
                            (11, "Novembre"),
                            (12, "Décembre"),
                        ],
                        verbose_name="mois",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("validated", "Validé"),
                            ("paid", "Payé"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="remarque"
                    ),
                ),
            ],
            options={
                "verbose_name": "cycle de paie",
                "verbose_name_plural": "cycles de paie",
                "ordering": ["-year", "-month"],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="salaire brut (DH)"
                    ),
                ),
                (
                    "cnss",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="CNSS salariale (DH)",
                    ),
                ),
                (
                    "amo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="AMO salariale (DH)",
                    ),
                ),
                (
                    "taxable",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="net imposable (DH)",
                    ),
                ),
                (
                    "family_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="déduction charges de famille (DH)",
                    ),
                ),
                (
                    "ir",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="IR (DH)"
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="salaire net (DH)"
                    ),
                ),
                (
                    "employer_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="coût employeur (DH)",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="hr.employee",
                        verbose_name="employé(e)",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="hr.payrollrun",
                        verbose_name="cycle de paie",
                    ),
                ),
            ],
            options={
                "verbose_name": "bulletin de paie",
                "verbose_name_plural": "bulletins de paie",
                "ordering": ["employee__last_name"],
                "unique_together": {("payroll_run", "employee")},
            },
        ),
    ]
