# Generated by Django 5.2.17 on 2026-08-18 17:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=60, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=60, verbose_name="nom")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Père"),
                            ("mother", "Mère"),
                            ("guardian", "Tuteur légal"),
                        ],
                        default="father",
                        max_length=10,
                        verbose_name="lien de parenté",
                    ),
                ),
                (
                    "cin",
                    models.CharField(
                        blank=True,
                        help_text="Carte d'identité nationale, ex. AB123456",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CIN invalide, ex. AB123456.",
                                regex="^[A-Za-z]{1,2}\\d{5,7}$",
                            )
                        ],
                        verbose_name="CIN",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro marocain attendu, ex. 0612345678 ou +212612345678.",
                                regex="^(\\+212|0)[5-8]\\d{8}$",
                            )
                        ],
                        verbose_name="téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="profession"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="adresse")),
            ],
            options={
                "verbose_name": "tuteur",
                "verbose_name_plural": "tuteurs",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date d'inscription",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Inscrit"),
                            ("transferred", "Transféré"),
                            ("withdrawn", "Retiré"),
                            ("graduated", "Diplômé"),
                        ],
                        default="active",
                        max_length=12,
                        verbose_name="statut",
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Remise accordée (fratrie, bourse…), en pourcentage.",
                        max_digits=5,
                        verbose_name="remise (%)",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="core.schoolclass",
                        verbose_name="classe",
                    ),
                ),
                (
                    "tuition_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="finance.tuitionplan",
                        verbose_name="formule de frais",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscription",
                "verbose_name_plural": "inscriptions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[("s1", "1er semestre"), ("s2", "2e semestre")],
                        max_length=2,
                        verbose_name="semestre",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Ex. : Contrôle 1, Devoir surveillé",
                        max_length=60,
                        verbose_name="intitulé",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="note (/20)"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.enrollment",
                        verbose_name="inscription",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades",
                        to="core.subject",
                        verbose_name="matière",
                    ),
                ),
            ],
            options={
                "verbose_name": "note",
                "verbose_name_plural": "notes",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=60, verbose_name="prénom (français)"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=60, verbose_name="nom (français)"),
                ),
                (
                    "first_name_ar",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="prénom (arabe)"
                    ),
                ),
                (
                    "last_name_ar",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="nom (arabe)"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Garçon"), ("F", "Fille")],
                        max_length=1,
                        verbose_name="sexe",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="date de naissance")),
                (
                    "birth_place",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="lieu de naissance"
                    ),
                ),
                (
                    "massar_code",
                    models.CharField(
                        blank=True,
                        help_text="Code national de l'élève (système Massar du ministère), ex. G123456789",
                        max_length=12,
                        verbose_name="code Massar",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="adresse")),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="Casablanca",
                        max_length=60,
                        verbose_name="ville",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro marocain attendu, ex. 0612345678 ou +212612345678.",
                                regex="^(\\+212|0)[5-8]\\d{8}$",
                            )
                        ],
                        verbose_name="téléphone",
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(blank=True, verbose_name="observations médicales"),
                ),
                (
                    "previous_school",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="établissement précédent",
                    ),
                ),
                (
                    "registered_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date d'inscription",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "guardians",
                    models.ManyToManyField(
                        blank=True,
                        related_name="students",
                        to="students.guardian",
                        verbose_name="tuteurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "élève",
                "verbose_name_plural": "élèves",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
                verbose_name="élève",
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="date"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("absent", "Absence"), ("late", "Retard")],
                        default="absent",
                        max_length=8,
                        verbose_name="type",
                    ),
                ),
                (
                    "justified",
                    models.BooleanField(default=False, verbose_name="justifiée"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="remarque"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="students.enrollment",
                        verbose_name="inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "absence / retard",
                "verbose_name_plural": "absences / retards",
                "ordering": ["-date"],
                "unique_together": {("enrollment", "date", "kind")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "school_class")},
        ),
    ]
