# Generated by Django 5.2.17 on 2026-08-18 23:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("hr", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviourRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date du fait",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("commendation", "Félicitations"),
                            ("encouragement", "Encouragements"),
                            ("remark", "Remarque"),
                            ("warning", "Avertissement"),
                            ("detention", "Retenue"),
                            ("exclusion", "Exclusion temporaire"),
                        ],
                        default="remark",
                        max_length=14,
                        verbose_name="nature",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="Ex. : bavardage répété, aide apportée à un camarade.",
                        max_length=120,
                        verbose_name="intitulé",
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="détails")),
                (
                    "follow_up",
                    models.CharField(
                        blank=True,
                        help_text="Sanction, entretien, mesure d'accompagnement…",
                        max_length=200,
                        verbose_name="suite donnée",
                    ),
                ),
                (
                    "guardians_informed",
                    models.BooleanField(default=False, verbose_name="tuteurs informés"),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behaviour_records",
                        to="students.enrollment",
                        verbose_name="inscription",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="behaviour_records",
                        to="hr.employee",
                        verbose_name="signalé par",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="behaviour_records",
                        to="core.subject",
                        verbose_name="matière / cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "fait de comportement",
                "verbose_name_plural": "comportement",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
