# Generated by Django 5.2.17 on 2026-08-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_tuitionplan_annual_fee_tuitionplan_billing_and_more"),
        ("students", "0002_behaviourrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="optional_fees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Manuels de la liste D achetés à l'école, options…",
                limit_choices_to={"mandatory": False},
                related_name="enrollments",
                to="finance.feeline",
                verbose_name="frais optionnels retenus",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="payment_plan",
            field=models.CharField(
                choices=[
                    ("upfront", "Comptant en début d'année (remise)"),
                    ("three", "3 versements"),
                    ("six", "6 versements"),
                    ("monthly", "Mensuel"),
                ],
                default="monthly",
                help_text="Le règlement comptant en début d'année ouvre droit à la remise prévue par la formule.",
                max_length=8,
                verbose_name="échéancier",
            ),
        ),
    ]
