# Generated by Django 5.2.17 on 2026-08-19 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_enrollment_optional_fees_enrollment_payment_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviourType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="nature"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="nature (arabe)"
                    ),
                ),
                (
                    "is_negative",
                    models.BooleanField(
                        default=True,
                        help_text="Décocher pour un fait positif (félicitations, encouragements, entraide…).",
                        verbose_name="fait négatif",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="ordre d'affichage"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="proposée à la saisie"
                    ),
                ),
            ],
            options={
                "verbose_name": "nature de fait",
                "verbose_name_plural": "natures de faits",
                "ordering": ["is_negative", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="behaviourrecord",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="students.behaviourtype",
                verbose_name="nature",
            ),
        ),
    ]
