# Generated by Django 5.2.17 on 2026-08-18 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("registration", "Frais d'inscription"),
                            ("tuition", "Mensualité"),
                            ("insurance", "Assurance scolaire"),
                            ("transport", "Transport scolaire"),
                            ("canteen", "Cantine"),
                            ("other", "Autre"),
                        ],
                        default="tuition",
                        max_length=12,
                        verbose_name="type de paiement",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (9, "Septembre"),
                            (10, "Octobre"),
                            (11, "Novembre"),
                            (12, "Décembre"),
                            (1, "Janvier"),
                            (2, "Février"),
                            (3, "Mars"),
                            (4, "Avril"),
                            (5, "Mai"),
                            (6, "Juin"),
                            (7, "Juillet"),
                        ],
                        help_text="Pour les mensualités : le mois couvert par ce paiement.",
                        null=True,
                        verbose_name="mois concerné",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="montant (DH)"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Espèces"),
                            ("cheque", "Chèque"),
                            ("transfer", "Virement bancaire"),
                            ("card", "Carte bancaire"),
                        ],
                        default="cash",
                        max_length=10,
                        verbose_name="mode de paiement",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="N° de chèque ou de virement.",
                        max_length=60,
                        verbose_name="référence",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="date de paiement",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="n° de reçu",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="remarque"
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "verbose_name_plural": "paiements",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TuitionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Payés une fois à l'inscription.",
                        max_digits=8,
                        verbose_name="frais d'inscription (DH)",
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Frais de scolarité mensuels.",
                        max_digits=8,
                        verbose_name="mensualité (DH)",
                    ),
                ),
                (
                    "insurance_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="assurance scolaire (DH)",
                    ),
                ),
                (
                    "months_count",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="En général 10 (septembre à juin).",
                        verbose_name="nombre de mensualités",
                    ),
                ),
            ],
            options={
                "verbose_name": "formule de frais",
                "verbose_name_plural": "formules de frais",
                "ordering": ["level__order"],
            },
        ),
    ]
