# Generated by Django 5.2.17 on 2026-08-18 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("finance", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="students.enrollment",
                verbose_name="inscription",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="encaissé par",
            ),
        ),
        migrations.AddField(
            model_name="tuitionplan",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuition_plans",
                to="core.academicyear",
                verbose_name="année scolaire",
            ),
        ),
        migrations.AddField(
            model_name="tuitionplan",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuition_plans",
                to="core.level",
                verbose_name="niveau",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tuitionplan",
            unique_together={("academic_year", "level")},
        ),
    ]
