# Generated by Django 5.2.17 on 2026-08-18 23:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage appliqué à la mensualité.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="remise demandée (%)",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("year", "Toute l'année scolaire"),
                            ("period", "Période déterminée"),
                        ],
                        default="year",
                        max_length=8,
                        verbose_name="portée",
                    ),
                ),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (9, "Septembre"),
                            (10, "Octobre"),
                            (11, "Novembre"),
                            (12, "Décembre"),
                            (1, "Janvier"),
                            (2, "Février"),
                            (3, "Mars"),
                            (4, "Avril"),
                            (5, "Mai"),
                            (6, "Juin"),
                            (7, "Juillet"),
                        ],
                        null=True,
                        verbose_name="du mois de",
                    ),
                ),
                (
                    "end_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (9, "Septembre"),
                            (10, "Octobre"),
                            (11, "Novembre"),
                            (12, "Décembre"),
                            (1, "Janvier"),
                            (2, "Février"),
                            (3, "Mars"),
                            (4, "Avril"),
                            (5, "Mai"),
                            (6, "Juin"),
                            (7, "Juillet"),
                        ],
                        null=True,
                        verbose_name="au mois de",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Fratrie, situation sociale, bourse, absence prolongée…",
                        verbose_name="motif",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("rejected", "Refusée"),
                        ],
                        default="pending",
                        editable=False,
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "requested_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="demandée le"),
                ),
                (
                    "decided_on",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="décidée le"
                    ),
                ),
                (
                    "decision_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="motif de la décision"
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="décision de",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_requests",
                        to="students.enrollment",
                        verbose_name="inscription",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_requests_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de remise",
                "verbose_name_plural": "demandes de remise",
                "ordering": ["-requested_on"],
                "permissions": [
                    (
                        "approve_discountrequest",
                        "Peut approuver ou refuser une demande de remise",
                    )
                ],
            },
        ),
    ]
