# Generated by Django 5.2.17 on 2026-08-19 00:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_school_alter_level_cycle_schoolclass_school"),
        ("finance", "0003_discountrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="tuitionplan",
            name="annual_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Facturation annuelle : montant global de la scolarité, frais d'inscription compris.",
                max_digits=9,
                verbose_name="scolarité annuelle (DH)",
            ),
        ),
        migrations.AddField(
            model_name="tuitionplan",
            name="billing",
            field=models.CharField(
                choices=[
                    ("monthly", "Mensuel (enseignement général)"),
                    ("annual", "Annuel (formation professionnelle et supérieure)"),
                ],
                default="monthly",
                max_length=8,
                verbose_name="mode de facturation",
            ),
        ),
        migrations.AddField(
            model_name="tuitionplan",
            name="cash_discount_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10"),
                help_text="Appliquée si la totalité est réglée en début d'année.",
                max_digits=5,
                verbose_name="remise paiement comptant (%)",
            ),
        ),
        migrations.AddField(
            model_name="tuitionplan",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuition_plans",
                to="core.school",
                verbose_name="établissement",
            ),
        ),
        migrations.CreateModel(
            name="FeeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("registration", "Inscription annuelle (FEA)"),
                            ("books_a", "Manuels — liste A (achat à l'école)"),
                            ("books_d", "Manuels — liste D (achat libre)"),
                            ("supplies", "Fournitures (papier, stylos…)"),
                            ("photocopy", "Photocopies et matériel"),
                            ("diploma", "Frais de diplôme"),
                            ("insurance", "Assurance scolaire"),
                            ("other", "Autre"),
                        ],
                        max_length=13,
                        verbose_name="nature",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Laisser vide pour reprendre l'intitulé de la nature.",
                        max_length=80,
                        verbose_name="intitulé",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="montant (DH)"
                    ),
                ),
                (
                    "mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Décocher pour la liste D : facturée seulement si la famille l'achète à l'école.",
                        verbose_name="obligatoire",
                    ),
                ),
                (
                    "due_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (9, "Septembre"),
                            (10, "Octobre"),
                            (11, "Novembre"),
                            (12, "Décembre"),
                            (1, "Janvier"),
                            (2, "Février"),
                            (3, "Mars"),
                            (4, "Avril"),
                            (5, "Mai"),
                            (6, "Juin"),
                            (7, "Juillet"),
                        ],
                        help_text="Laisser vide pour inclure ce frais dans l'échéancier. Le diplôme, par exemple, se règle à part au 6e mois.",
                        null=True,
                        verbose_name="exigible au mois de",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.tuitionplan",
                        verbose_name="formule",
                    ),
                ),
            ],
            options={
                "verbose_name": "frais annexe",
                "verbose_name_plural": "frais annexes",
                "ordering": ["kind", "id"],
            },
        ),
    ]
