# Generated by Django 5.2.17 on 2026-08-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_school_alter_level_cycle_schoolclass_school"),
        ("finance", "0004_tuitionplan_annual_fee_tuitionplan_billing_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tuitionplan",
            unique_together={("academic_year", "level", "school")},
        ),
    ]
