# Generated by Django 5.2.17 on 2026-08-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Format : 2026-2027",
                        max_length=9,
                        unique=True,
                        verbose_name="année scolaire",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="date de début")),
                ("end_date", models.DateField(verbose_name="date de fin")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="année en cours"),
                ),
            ],
            options={
                "verbose_name": "année scolaire",
                "verbose_name_plural": "années scolaires",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle",
                    models.CharField(
                        choices=[
                            ("preschool", "Préscolaire"),
                            ("primary", "Primaire"),
                            ("middle", "Collège"),
                            ("high", "Lycée"),
                        ],
                        max_length=12,
                        verbose_name="cycle",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ex. : 1AP, 6AP, 3AC, TC, 1BAC, 2BAC",
                        max_length=10,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=80, verbose_name="nom (français)"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="nom (arabe)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordre"),
                ),
            ],
            options={
                "verbose_name": "niveau",
                "verbose_name_plural": "niveaux",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=80, verbose_name="nom (français)"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="nom (arabe)"
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=1,
                        default=1,
                        max_digits=4,
                        verbose_name="coefficient",
                    ),
                ),
            ],
            options={
                "verbose_name": "matière",
                "verbose_name_plural": "matières",
                "ordering": ["name_fr"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex. : A, B, Groupe 1",
                        max_length=40,
                        verbose_name="nom de la classe",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="capacité"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="core.academicyear",
                        verbose_name="année scolaire",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="core.level",
                        verbose_name="niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "classe",
                "verbose_name_plural": "classes",
                "ordering": ["level__order", "name"],
            },
        ),
    ]
