# Generated by Django 5.2.17 on 2026-08-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="main_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_led",
                to="hr.employee",
                verbose_name="professeur principal",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schoolclass",
            unique_together={("academic_year", "level", "name")},
        ),
    ]
