# Generated by Django 5.2.17 on 2026-08-19 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="établissement"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="établissement (arabe)"
                    ),
                ),
                (
                    "programme",
                    models.CharField(
                        choices=[
                            ("general", "Enseignement général"),
                            ("vocational", "Formation professionnelle et supérieure"),
                        ],
                        default="general",
                        max_length=12,
                        verbose_name="type de programme",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="Casablanca",
                        max_length=60,
                        verbose_name="ville",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="adresse"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=13, verbose_name="téléphone"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "établissement",
                "verbose_name_plural": "établissements",
                "ordering": ["programme", "name"],
            },
        ),
        migrations.AlterField(
            model_name="level",
            name="cycle",
            field=models.CharField(
                choices=[
                    ("preschool", "Préscolaire"),
                    ("primary", "Primaire"),
                    ("middle", "Collège"),
                    ("high", "Lycée"),
                    ("vocational", "Formation professionnelle"),
                    ("higher", "Enseignement supérieur"),
                ],
                max_length=12,
                verbose_name="cycle",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="core.school",
                verbose_name="établissement",
            ),
        ),
    ]
